name: dnd_helper
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-10.0.dev <3.0.0'


dependencies:
  auto_route: ^3.2.4
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.1
  http: ^0.13.4
  hydrated_bloc: ^8.1.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.6
  path_provider: ^2.0.9
  

dev_dependencies:
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon_1.png"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
  