/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
library;
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values, constant_identifier_names

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData book_1 =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadsword =
      IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campfire =
      IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magic =
      IconData(0xf0d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copyright =
      IconData(0xf1f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_end =
      IconData(0xf253, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData registered =
      IconData(0xf25d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person =
      IconData(0xf3c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campground =
      IconData(0xf6bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
